name: bus_karo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4
  
dependencies:
  flutter:
    sdk: flutter

  # Standard Icons
  cupertino_icons: ^1.0.2

  # Driver & Firebase Packages
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4

  # Student Packages
  google_maps_flutter: ^2.5.3
  geolocator: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
